/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subtask = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Outcome = IDL.Variant({
  'avoided' : IDL.Null,
  'completed' : IDL.Null,
});
export const TaskState = IDL.Variant({
  'active' : IDL.Null,
  'avoided' : IDL.Null,
  'idle' : IDL.Null,
  'completed' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'skipCount' : IDL.Nat,
  'state' : TaskState,
  'subtasks' : IDL.Vec(Subtask),
  'difficultyMultiplier' : IDL.Float64,
  'estimatedMinutes' : IDL.Nat,
});
export const Stats = IDL.Record({
  'currentBurdenScore' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'avoidedCount' : IDL.Nat,
  'totalFocusMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'carryOverTasks' : IDL.Func([], [], []),
  'coachQuery' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(Subtask)],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'endSession' : IDL.Func([IDL.Text, Outcome, IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'startSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTask' : IDL.Func([IDL.Text, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subtask = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const Outcome = IDL.Variant({ 'avoided' : IDL.Null, 'completed' : IDL.Null });
  const TaskState = IDL.Variant({
    'active' : IDL.Null,
    'avoided' : IDL.Null,
    'idle' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'skipCount' : IDL.Nat,
    'state' : TaskState,
    'subtasks' : IDL.Vec(Subtask),
    'difficultyMultiplier' : IDL.Float64,
    'estimatedMinutes' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'currentBurdenScore' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'avoidedCount' : IDL.Nat,
    'totalFocusMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    'carryOverTasks' : IDL.Func([], [], []),
    'coachQuery' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(Subtask)],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'endSession' : IDL.Func([IDL.Text, Outcome, IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'startSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTask' : IDL.Func([IDL.Text, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };