/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Outcome = { 'avoided' : null } |
  { 'completed' : null };
export interface Stats {
  'currentBurdenScore' : bigint,
  'completedCount' : bigint,
  'avoidedCount' : bigint,
  'totalFocusMinutes' : bigint,
}
export interface Subtask {
  'id' : string,
  'title' : string,
  'completed' : boolean,
}
export interface Task {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'skipCount' : bigint,
  'state' : TaskState,
  'subtasks' : Array<Subtask>,
  'difficultyMultiplier' : number,
  'estimatedMinutes' : bigint,
}
export type TaskState = { 'active' : null } |
  { 'avoided' : null } |
  { 'idle' : null } |
  { 'completed' : null };
export interface _SERVICE {
  'carryOverTasks' : ActorMethod<[], undefined>,
  'coachQuery' : ActorMethod<[string], string>,
  'createTask' : ActorMethod<
    [string, string, bigint, Array<Subtask>],
    undefined
  >,
  'deleteTask' : ActorMethod<[string], undefined>,
  'endSession' : ActorMethod<[string, Outcome, bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getStats' : ActorMethod<[], Stats>,
  'getTask' : ActorMethod<[string], Task>,
  'startSession' : ActorMethod<[string, string], undefined>,
  'updateTask' : ActorMethod<[string, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];