/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: string;
    title: string;
    createdAt: bigint;
    skipCount: bigint;
    state: TaskState;
    subtasks: Array<Subtask>;
    difficultyMultiplier: number;
    estimatedMinutes: bigint;
}
export interface Subtask {
    id: string;
    title: string;
    completed: boolean;
}
export interface Stats {
    currentBurdenScore: bigint;
    completedCount: bigint;
    avoidedCount: bigint;
    totalFocusMinutes: bigint;
}
export enum Outcome {
    avoided = "avoided",
    completed = "completed"
}
export enum TaskState {
    active = "active",
    avoided = "avoided",
    idle = "idle",
    completed = "completed"
}
export interface backendInterface {
    carryOverTasks(): Promise<void>;
    coachQuery(message: string): Promise<string>;
    createTask(id: string, title: string, estimatedMinutes: bigint, subtasks: Array<Subtask>): Promise<void>;
    deleteTask(id: string): Promise<void>;
    endSession(id: string, outcome: Outcome, minutesSpent: bigint): Promise<void>;
    getAllTasks(): Promise<Array<Task>>;
    getStats(): Promise<Stats>;
    getTask(id: string): Promise<Task>;
    startSession(id: string, taskId: string): Promise<void>;
    updateTask(id: string, task: Task): Promise<void>;
}
import type { Outcome as _Outcome, Subtask as _Subtask, Task as _Task, TaskState as _TaskState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async carryOverTasks(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.carryOverTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.carryOverTasks();
            return result;
        }
    }
    async coachQuery(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.coachQuery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.coachQuery(arg0);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: bigint, arg3: Array<Subtask>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async endSession(arg0: string, arg1: Outcome, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0, to_candid_Outcome_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0, to_candid_Outcome_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getTask(arg0: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async startSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: string, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TaskState_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskState): TaskState {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: bigint;
    skipCount: bigint;
    state: _TaskState;
    subtasks: Array<_Subtask>;
    difficultyMultiplier: number;
    estimatedMinutes: bigint;
}): {
    id: string;
    title: string;
    createdAt: bigint;
    skipCount: bigint;
    state: TaskState;
    subtasks: Array<Subtask>;
    difficultyMultiplier: number;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        skipCount: value.skipCount,
        state: from_candid_TaskState_n6(_uploadFile, _downloadFile, value.state),
        subtasks: value.subtasks,
        difficultyMultiplier: value.difficultyMultiplier,
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    avoided: null;
} | {
    idle: null;
} | {
    completed: null;
}): TaskState {
    return "active" in value ? TaskState.active : "avoided" in value ? TaskState.avoided : "idle" in value ? TaskState.idle : "completed" in value ? TaskState.completed : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Outcome_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): _Outcome {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TaskState_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskState): _TaskState {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: bigint;
    skipCount: bigint;
    state: TaskState;
    subtasks: Array<Subtask>;
    difficultyMultiplier: number;
    estimatedMinutes: bigint;
}): {
    id: string;
    title: string;
    createdAt: bigint;
    skipCount: bigint;
    state: _TaskState;
    subtasks: Array<_Subtask>;
    difficultyMultiplier: number;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        skipCount: value.skipCount,
        state: to_candid_TaskState_n10(_uploadFile, _downloadFile, value.state),
        subtasks: value.subtasks,
        difficultyMultiplier: value.difficultyMultiplier,
        estimatedMinutes: value.estimatedMinutes
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskState): {
    active: null;
} | {
    avoided: null;
} | {
    idle: null;
} | {
    completed: null;
} {
    return value == TaskState.active ? {
        active: null
    } : value == TaskState.avoided ? {
        avoided: null
    } : value == TaskState.idle ? {
        idle: null
    } : value == TaskState.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): {
    avoided: null;
} | {
    completed: null;
} {
    return value == Outcome.avoided ? {
        avoided: null
    } : value == Outcome.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
